### ISSUE TITLE
Getting Error: [Cake\View\Exception\MissingTemplateException]

### ISSUE THREAD

**Issue by kevindecapite** [slince/cakephp-pjax#1]
This may not have to do with your plugin, but I'm getting the following exception when attempting to navigate to valid URLs w/in my app, using your plugin with PJAX:

```
2018-08-22 06:45:45 Error: [Cake\View\Exception\MissingTemplateException] Template file "Phenomena/manage.ctp" is missing.
Exception Attributes: array (
  'file' => 'Phenomena/manage.ctp',
)
Request URL: /phenomena/add
Referer URL: https://luna.local/phenomena/add
Stack Trace:
#0 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/View/View.php(768): Cake\View\View->_getViewFileName('Phenomena/manag...')
#1 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Controller/Controller.php(623): Cake\View\View->render('manage', NULL)
#2 /home/vagrant/www/luna/app/src/Controller/PhenomenaController.php(80): Cake\Controller\Controller->render('manage')
#3 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\PhenomenaController->add()
#4 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#5 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PhenomenaController))
#6 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 /home/vagrant/www/luna/app/vendor/slince/cakephp-pjax/src/Middleware/PjaxMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Slince\Pjax\Middleware\PjaxMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 /home/vagrant/www/luna/app/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /home/vagrant/www/luna/app/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /home/vagrant/www/luna/app/webroot/index.php(40): Cake\Http\Server->run()
#21 {main}
```

If I go to the URL directly (not by clicking a link), I do not see this error. I am running all my templates via a "theme" (i.e. Cake plugin), in case that makes a difference.

Cheers!

**Comment by slince** [comment]
Hi,  can you tell me what version of CakePHP you are using?

**Comment by slince** [comment]
If you disable the plugin, will you get this error?

**Comment by kevindecapite** [comment]
I'm on Cake 3.5.14 and the error occurs with and without the plugin. So perhaps this is an issue with pjax itself, or how it's implemented? However, I'm using a store-bought theme and using their JS as-is. I only see this error when running it through the Cake framework.

Thank you for writing back.
